import sys
if sys.version_info[0] == 3:
    from urllib.request import urlopen
else:
    from urllib import urlopen


def format_lex(ifile, ofile, define=False, title="Untitled"):
    # Get lexicon from file
    lextext = open(ifile, "r").read()
    lex = []
    texts = lextext.split("\n")
    for i in texts:
        lex.append(i.split(", "))

    # Header HTML
    html = """<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>"""+title+"""</title>
        <style>
            tr:nth-child(even) {background: #DDD}
            tr:nth-child(odd) {background: #CCC}
            body {background-color: #CCC;font-family: sans-serif;}
        </style>
    </head>
    <body>
        <h1>"""+title+"""</h1>
        <h3>Generated by <a href="https://github.com/Property404/MedLex">MedLex</a></h3>
        <table>
            <tr>
                <td><strong>Word</strong></td>
                <td><strong>Other forms</strong></td>"""
    if define:
        html += "\n\t\t\t\t<td><strong>Definition</strong></td>"
    html += "\n\t\t\t</tr>\n"

    # HTML body
    it = 0
    for i in lex:
        i[0] = i[0].title()

        # If no vowels, it must be all uppercase
        for j in "aeiou-":
            if j == "-":
                i[0] = i[0].upper()
            if j not in i[0]:
                continue
            break
        it += 1

        sys.stdout.write("Writing... "+str(it)+"/"+str(len(lex))+"\r")
        html += "\t\t\t<tr>\n\t\t\t\t<td>"+i[0]+"</td>\n\t\t\t\t<td>"
        if len(i) > 1:
            for j in i[1::]:
                if j != i[-1]:
                    html += j
                else:
                    break
                html += "<br />"
        html += "</td>"

        if define:
            dsource = urlopen("http://dictionary.reference.com/browse/"+i[0]).read()
            if sys.version_info[0] >= 3:
                dsource = dsource.decode("utf-8")
            definition = ""
            if "Did you mean" not in dsource:
                try:
                    dsource = dsource[dsource.index("\n<div class=\"def-content\">")::]
                    definition = dsource[0:dsource.index("</div>")]
                    definition = definition.replace("\n", "\n\t\t\t\t\t")
                    definition += (definition.count("<div")*"</div>")+"\n\t\t\t\t"
                except:
                    definition = "-"
            html += "\n\t\t\t\t<td>"+definition
            html += "</td>"

        html += "\n\t\t\t</tr>\n"

    # HTML tail
    html += """\t\t</table>
    </body>
</html>
"""

    # Export
    print("")
    html = str(u''.join([k if ord(k) < 128 else '' for k in html]))
    f = open(ofile, "w")
    f.write(html)
    f.close()